
- name: install pkg for docker
  yum:
     name: "{{ item.pkg }}"
     state: "{{ item.version }}"
  with_items:
     - { pkg: yum-utils,                     version: latest }
     - { pkg: device-mapper-persistent-data, version: latest }
     - { pkg: lvm2,                          version: latest }

- name: add docker Repositories
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker
  yum:
     name: docker-ce
     state: latest

- name: start docker.service and set enabled
  systemd:
     name: docker
     state: started
     enabled: yes

- name: install docker-compose
  get_url:
     url: "{{ docker_compose_download_url }}"
     dest: "{{ docker_compose_install_path }}"

- name: change permission
  file:
     path: "{{ docker_compose_install_path }}"
     mode: 755
